services:
  - type: web
    name: parakh-ai
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y tesseract-ocr
    startCommand: gunicorn app:app